import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root',
})
export class reRateService {

  constructor() {


  }

}


export class ReRateMasterService {
  country: string;
  note: string;
  passport: boolean;
  wificall: boolean;
  daypass: boolean;
  domesticeligibility: boolean;
  planname: string;
  cost: string;
  ppurates: boolean;
  adjustmentrate: number;
  roamingcharges: number;
}


export const ReRateMasaters: ReRateMasterService[] =

  [
  {
    country: "Angola",
    note: "",
    passport: true,
    wificall: false,
    daypass: false,
    domesticeligibility: false,
    planname: "",
    cost: '',
      ppurates: true,
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Airlines (on-air)",
    note: "Only pay-per-use 'Airline' rates apply",
    passport: false,
    wificall: true,
    daypass: false,
    domesticeligibility: false,
    planname: "",
    cost:'',
      ppurates: true,
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Aland Islands (Finland)",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    domesticeligibility: true,
    planname: "",
    cost:'',
      ppurates: true,
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Algeria",
    note: "this is another test note",
    passport: true,
    wificall: true,
    daypass: true,
    domesticeligibility: true,
    planname: "",
    cost:'',
    ppurates: true,
    adjustmentrate: 1000,
    roamingcharges: 1000
  },
  {
    country: "Afghanistan",
    note: "",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Airlines (on-air)",
    note: "Only pay-per-use Airline rates apply",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Aland Islands (Finland)",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Albania",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "American Samoa",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Andorra",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Angola",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Anguilla",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Antarctica (Marambio Base)",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Antigua & Barbuda",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Argentina",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Armenia",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Aruba",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Ascension Island",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },
  {
    country: "Australia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },  
  {
    country: "Austria",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },  
  {
    country: "Azerbaijan",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },  
  {
    country: "Bahamas",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Bahrain",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Bangladesh",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Barbados",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Belarus",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Belgium",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Belize",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Benin",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Bermuda",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Bhutan",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Bolivia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Bonaire, St. Eustatius & Saba",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Bosnia & Herzegovina",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Botswana",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Brazil",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "British Virgin Islands",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Brunei",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Bulgaria",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Burkina Faso",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Burundi",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Cambodia",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Cameroon",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Canada",
    note: "Roam North America! - Available for customers of AT&T Unlimited Plan",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Cape Verde",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },  {
    country: "Cayman Islands",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Central African Republic",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Chad",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Chile",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "China",
    note: "",
    passport: true,
    wificall: false,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Christmas Island",
    note: "",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Colombia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Comoros",
    note: "",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Congo, Democratic Rep. of (Zaire)",
    note: "",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Congo, Rep. of",
    note: "",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Cook Islands",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Costa Rica",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Croatia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Cruise Ships",
    note: "Go to att.com/cruiseships to validate ship participates in AT&T plans",
    passport: false,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Cuba",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: false,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Curaçao",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Cyprus",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Czech Republic",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },  {
    country: "Denmark",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Djibouti",
    note: "",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 

  {
    country: "Dominica",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Dominican Republic",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "East Timor",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Easter Island",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Ecuador",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Egypt",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "El Salvador",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Equatorial Guinea",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Eritrea",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: false,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Estonia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Ethiopia",
    note: "",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Falkland Islands",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Faroe Islands",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Fiji",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Finland",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "France",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "French Guiana",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "French Polynesia (Tahiti)",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Gabon",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Gambia",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 

  {
    country: "Georgia",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Germany",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Ghana",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Gibraltar",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 

  {
    country: "Gibraltar (Africa)",
    note: "",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Greece",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Greenland",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Grenada",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Guadeloupe",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Guam",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Guatemala",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Guernsey",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Guinea",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Guinea - Bissau",
    note: "",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Guyana",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Haiti",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Honduras",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Hong Kong",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Hungary",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Iceland",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "India",
    note: "",
    passport: true,
    wificall: false,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Indonesia",
    note: "",
    passport: false,
    wificall: false,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Iraq",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Ireland",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Isle of Man",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Israel",
    note: "",
    passport: true,
    wificall: false,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Italy",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Ivory Coast (Cote D'Ivoire)",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Jamaica",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Japan",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Jersey",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Jordan",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Kazakhstan",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Kenya",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Kosovo",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Kuwait",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Kyrgyzstan",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Laos",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Latvia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Lebanon",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Lesotho",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Liberia",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Libya",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Liechtenstein",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Lithuania",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Luxembourg",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Macao (Macau)",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Macedonia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Madagascar",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Malawi",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Malaysia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Maldives",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Mali",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Malta",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Martinique",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Mauritania",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Mauritius",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Mayotte",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Mexico",
    note: "Roam Mexico! - Available for customers on 15GB+ Mobile Share Value and 10GB+ Mobile Share Advantage",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Micronesia",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Moldova",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Monaco",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Mongolia, Rep. of",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Montenegro",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Montserrat",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Morocco",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Mozambique",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Myanmar",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Namibia",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Nauru",
    note: "",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Nepal",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Netherlands",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Netherlands Antilles  (includes Curacao only)",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "New Caledonia",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "New Zealand",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Nicaragua",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Niger",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Nigeria",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Norfolk Island",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "North Korea",
    note: "Are you sure you didn't mean South Korea?",
    passport: false,
    wificall: false,
    daypass: false,
    ppurates: false,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Northern Mariana Islands",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Norway",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Oman",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Pakistan",
    note: "",
    passport: true,
    wificall: false,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Palau",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Palestinian Authority",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Panama",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Papua New Guinea",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Paraguay",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Peru",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Philippines",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Poland",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Portugal",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Qatar",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Reunion Island",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Romania",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Russia",
    note: "Free roaming in Russia for customer during the World Cup - June 14 - July 15, 2018. See myCSP *672957 for details!",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Rwanda, Rep. of",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Samoa (Western)",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "San Marino",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Säo Tomé & Principe",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  

  {
    country: "Saudi Arabia",
    note: "",
    passport: true,
    wificall: false,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Senegal",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Serbia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Seychelles",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  

  {
    country: "Sierra Leone",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Singapore",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Slovakia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  

  {
    country: "Slovenia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  

  {
    country: "Solomon Islands",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Somalia",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "South Africa",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "South Korea",
    note: "February 1, 2018 - March 20, 2018 - daily fee for IDP waived - all days in South Korea during this time do not count towards 'days with usage'",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "South Sudan",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  

  {
    country: "Spain",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Sri Lanka",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "St. Barthelemy",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "St. Kitts & Nevis",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "St. Lucia",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "St. Maarten",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "St. Martin",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "t. Pierre & Miquelon",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  

  {
    country: "St. Vincent & the Grenadines",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Sudan",
    note: "",
    passport: true,
    wificall: false,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  
  {
    country: "Suriname",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Svalbard",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Swaziland",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Sweden",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Switzerland",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Syrian Arab Republic",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: false,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Taiwan",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Tajikistan",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Tanzania",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Thailand",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Togo",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: true,
    wificall: true,
    daypass:false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Tonga",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Trinidad & Tobago",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Tunisia",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Turkey",
    note: "",
    passport: true,
    wificall: false,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Turkmenistan",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: false,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Turks & Caicos",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Uganda",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Ukraine",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "United Arab Emirates",
    note: "",
    passport: true,
    wificall: false,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "United Kingdom",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Uruguay",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Uzbekistan",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Vanuatu",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Vatican City",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Venezuela",
    note: "",
    passport: true,
    wificall: true,
    daypass: true,
    ppurates: true,
    domesticeligibility: true,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Vietnam",
    note: "You can double-check passport eligibility at att.com/globalcountries",
    passport: true,
    wificall: false,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Western Sahara",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Yemen",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Zambia",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  }, 
  {
    country: "Zimbabwe",
    note: "",
    passport: true,
    wificall: true,
    daypass: false,
    ppurates: true,
    domesticeligibility: false,
    planname: "",
    cost:'',      
      adjustmentrate: 1000,
      roamingcharges : 1000
  },   

  ]


